POST http://localhost:3000/api/post
content-type: application/json

{
    "title": "formula 1 titulo teste",
    "subtitle": "Boxe subtitulo teste",
    "image": "https://media.formula1.com/image/upload/content/dam/fom-website/sutton/2022/Italy/Sunday/1422823415.jpg",
    "text": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum"
}


###
GET  http://localhost:3000/api/post


###
GET  http://localhost:3000/api/post/648b9eec3198494678f7c69d

###
DELETE   http://localhost:3000/api/post/648e6c39fcd31d627c7ad0c5

###
put http://localhost:3000/api/post/648cfc50284caed7e337d75c
content-type: application/json

{
    "title": "Teste inicial atualizado",
    "subtitle": "Subtitulo inicial",
    "image": "https://poolrescue.com.br/wp-content/uploads/2016/04/nata%C3%A7%C3%A3o-1200x800.jpg",
    "text": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}


###
POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "name": "Admin",
    "email": "admin@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "12345"
}
